const translations = {
  bg: { home: 'Начало', products: 'Продукти', manufacturing: 'Производство', about: 'За нас', contact: 'Контакт', heroTitleLine1: 'Създаваме мебели', heroTitleLine2: 'с любов и майсторство', heroSubtitle: 'Всеки продукт е изработен ръчно в нашата работилница с внимание към всеки детайл', heroButton1: 'Разгледай продуктите', heroButton2: 'Нашето производство', categoriesTitle: 'Нашите категории', categoriesSubtitle: 'Открийте перфектните мебели за вашия дом от нашите специализирани колекции', divani: 'Дивани', spalni: 'Спални', stolove: 'Столове', masi: 'Маси', productsTitle: 'Нашите продукти', productsSubtitle: 'Разгледайте нашите колекции, създадени с внимание към всеки детайл', viewAll: 'Виж всички', details: 'Детайли', onRequest: 'По запитване', manufacturingTitle: 'Ние сме производители', manufacturingSubtitle: 'За разлика от други, ние не внасяме или препродаваме мебели. Всеки продукт е създаден в нашата работилница с любов и внимание към детайлите.', manufacturingWorkshopTitle: 'Нашата работилница', manufacturingWorkshopText: 'В сърцето на нашето производство се намира модерна работилница, оборудвана с най-новите технологии и водена от опитни майстори с десетилетия опит.', manufacturingFeature1: 'Ръчна изработка на всеки продукт', manufacturingFeature2: 'Използване на премиум материали', manufacturingFeature3: 'Индивидуален подход към всеки клиент', manufacturingFeature4: 'Гаранция за качество и дълготрайност', aboutTitle: 'Нашата история', aboutText1: 'Започнахме като малка семейна работилница с мечтата да създаваме мебели, които не само са красиви, но и издържливи. Днес, след 15 години упорита работа, сме горди, че можем да предложим на нашите клиенти продукти от най-високо качество.', aboutText2: 'Всеки продукт носи частичка от нашата страст към майсторството и стремежа ни към съвършенство. Ние не просто правим мебели - ние създаваме произведения на изкуството за вашия дом.', satisfiedClients: 'Доволни клиенти', yearsExperience: 'Години опит', contactTitle: 'Свържете се с нас', contactSubtitle: 'Готови сме да отговорим на всички ваши въпроси и да ви помогнем с избора на перфектните мебели', contactInfo: 'Информация за контакт', phone: 'Телефон', email: 'Email', address: 'Адрес', sendInquiry: 'Изпратете запитване', yourName: 'Вашето име', yourEmail: 'Вашият email', yourPhone: 'Вашият телефон', yourMessage: 'Вашето съобщение', sendButton: 'Изпрати запитване', footerDescription: 'Производители на висококачествени луксозни мебели за вашия дом. Всеки продукт е създаден с любов и внимание към детайлите.', navigation: 'Навигация', contacts: 'Контакт', newsletter: 'Бюлетин', newsletterPlaceholder: 'Вашият имейл', allRightsReserved: 'Всички права запазени.', new: 'Ново' },
  en: { home: 'Home', products: 'Products', manufacturing: 'Manufacturing', about: 'About', contact: 'Contact', heroTitleLine1: 'We create furniture', heroTitleLine2: 'with love and craftsmanship', heroSubtitle: 'Every product is handcrafted in our workshop with attention to every detail', heroButton1: 'View Products', heroButton2: 'Our Manufacturing', categoriesTitle: 'Our Categories', categoriesSubtitle: 'Discover the perfect furniture for your home from our specialized collections', divani: 'Sofas', spalni: 'Bedrooms', stolove: 'Chairs', masi: 'Tables', productsTitle: 'Our Products', productsSubtitle: 'Explore our collections, created with attention to every detail', viewAll: 'View All', details: 'Details', onRequest: 'On Request', manufacturingTitle: 'We are manufacturers', manufacturingSubtitle: 'Unlike others, we don\'t import or resell furniture. Every product is created in our workshop with love and attention to detail.', manufacturingWorkshopTitle: 'Our Workshop', manufacturingWorkshopText: 'At the heart of our production is a modern workshop, equipped with the latest technologies and led by experienced craftsmen with decades of experience.', manufacturingFeature1: 'Handcrafted every product', manufacturingFeature2: 'Using premium materials', manufacturingFeature3: 'Individual approach to every client', manufacturingFeature4: 'Quality and durability guarantee', aboutTitle: 'Our Story', aboutText1: 'We started as a small family workshop with the dream of creating furniture that is not only beautiful but also durable. Today, after 15 years of hard work, we are proud to offer our customers the highest quality products.', aboutText2: 'Every product carries a piece of our passion for craftsmanship and our pursuit of perfection. We don\'t just make furniture - we create works of art for your home.', satisfiedClients: 'Satisfied Clients', yearsExperience: 'Years Experience', contactTitle: 'Contact Us', contactSubtitle: 'We are ready to answer all your questions and help you choose the perfect furniture', contactInfo: 'Contact Information', phone: 'Phone', email: 'Email', address: 'Address', sendInquiry: 'Send Inquiry', yourName: 'Your Name', yourEmail: 'Your Email', yourPhone: 'Your Phone', yourMessage: 'Your Message', sendButton: 'Send Inquiry', footerDescription: 'Manufacturers of high-quality luxury furniture for your home. Every product is created with love and attention to detail.', navigation: 'Navigation', contacts: 'Contact', newsletter: 'Newsletter', newsletterPlaceholder: 'Your email', allRightsReserved: 'All rights reserved.', new: 'New' },
  el: { home: 'Αρχική', products: 'Προϊόντα', manufacturing: 'Παραγωγή', about: 'Σχετικά', contact: 'Επικοινωνία', heroTitleLine1: 'Δημιουργούμε έπιπλα', heroTitleLine2: 'με αγάπη και τεχνογνωσία', heroSubtitle: 'Κάθε προϊόν είναι χειροποίητο στο εργαστήριό μας με προσοχή σε κάθε λεπτομέρεια', heroButton1: 'Δείτε Προϊόντα', heroButton2: 'Η Παραγωγή μας', categoriesTitle: 'Οι Κατηγορίες μας', categoriesSubtitle: 'Ανακαλύψτε τα τέλεια έπιπλα για το σπίτι σας από τις εξειδικευμένες συλλογές μας', divani: 'Καναπέδες', spalni: 'Υπνοδωμάτια', stolove: 'Καρέκλες', masi: 'Τραπέζια', productsTitle: 'Τα Προϊόντα μας', productsSubtitle: 'Εξερευνήστε τις συλλογές μας, δημιουργημένες με προσοχή σε κάθε λεπτομέρεια', viewAll: 'Δείτε Όλα', details: 'Λεπτομέρειες', onRequest: 'Κατόπιν Αιτήματος', manufacturingTitle: 'Είμαστε κατασκευαστές', manufacturingSubtitle: 'Σε αντίθεση με άλλους, δεν εισάγουμε ή μεταπωλούμε έπιπλα. Κάθε προϊόν δημιουργείται στο εργαστήριό μας με αγάπη και προσοχή στις λεπτομέρειες.', manufacturingWorkshopTitle: 'Το Εργαστήριό μας', manufacturingWorkshopText: 'Στην καρδιά της παραγωγής μας βρίσκεται ένα σύγχρονο εργαστήριο, εξοπλισμένο με τις πιο σύγχρονες τεχνολογίες και διευθυνόμενο από έμπειρους τεχνίτες με δεκαετίες εμπειρίας.', manufacturingFeature1: 'Χειροποίητη κατασκευή κάθε προϊόντος', manufacturingFeature2: 'Χρήση premium υλικών', manufacturingFeature3: 'Ατομική προσέγγιση σε κάθε πελάτη', manufacturingFeature4: 'Εγγύηση ποιότητας και αντοχής', aboutTitle: 'Η Ιστορία μας', aboutText1: 'Ξεκινήσαμε ως ένα μικρό οικογενειακό εργαστήριο με το όνειρο να δημιουργούμε έπιπλα που δεν είναι μόνο όμορφα αλλά και ανθεκτικά. Σήμερα, μετά από 15 χρόνια σκληρής δουλειάς, είμαστε περήφανοι που μπορούμε να προσφέρουμε στους πελάτες μας προϊόντα υψηλότερης ποιότητας.', aboutText2: 'Κάθε προϊόν φέρει ένα κομμάτι από το πάθος μας για την τεχνοτροπία και την επιδίωξή μας για τελειότητα. Δεν φτιάχνουμε απλώς έπιπλα - δημιουργούμε έργα τέχνης για το σπίτι σας.', satisfiedClients: 'Ικανοποιημένοι Πελάτες', yearsExperience: 'Χρόνια Εμπειρίας', contactTitle: 'Επικοινωνήστε μαζί μας', contactSubtitle: 'Είμαστε έτοιμοι να απαντήσουμε σε όλες τις ερωτήσεις σας και να σας βοηθήσουμε να επιλέξετε τα τέλεια έπιπλα', contactInfo: 'Στοιχεία Επικοινωνίας', phone: 'Τηλέφωνο', email: 'Email', address: 'Διεύθυνση', sendInquiry: 'Στείλτε Ερώτηση', yourName: 'Το Όνομά σας', yourEmail: 'Το Email σας', yourPhone: 'Το Τηλέφωνό σας', yourMessage: 'Το Μήνυμά σας', sendButton: 'Στείλτε Ερώτηση', footerDescription: 'Κατασκευαστές υψηλής ποιότητας πολυτελών επίπλων για το σπίτι σας. Κάθε προϊόν δημιουργείται με αγάπη και προσοχή στις λεπτομέρειες.', navigation: 'Πλοήγηση', contacts: 'Επικοινωνία', newsletter: 'Ενημερωτικό Δελτίο', newsletterPlaceholder: 'Το email σας', allRightsReserved: 'Όλα τα δικαιώματα διατηρούνται.', new: 'Νέο' }
};

let currentLang = localStorage.getItem('language') || 'bg';

const I18N = {
  t: (key) => translations[currentLang][key] || translations.bg[key] || key,
  setLanguage: (lang) => {
    currentLang = lang;
    localStorage.setItem('language', lang);
    I18N.updatePage();
  },
  getCurrentLanguage: () => currentLang,
  updatePage: () => {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      el.textContent = I18N.t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      el.placeholder = I18N.t(key);
    });
    const langBtns = document.querySelectorAll('.lang-btn');
    langBtns.forEach(btn => {
      btn.classList.toggle('active', btn.getAttribute('data-lang') === currentLang);
    });
  },
  getTranslatedProductField: (product, field) => {
    if (product.translations && product.translations[currentLang] && product.translations[currentLang][field]) {
      return product.translations[currentLang][field];
    }
    if (product.translations && product.translations.bg && product.translations.bg[field]) {
      return product.translations.bg[field];
    }
    return product[field] || '';
  }
};
